import { Layout } from "@/components/layout"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <Layout>
        <body>{children}</body>
      </Layout>
    </html>
  )
}
